project:
  type: website

website:
  title: "ReNAF"
  navbar:
    background: primary
    search: true
  sidebar:
    background: primary
    style: "docked"
    contents:
      - index.qmd
      - Cantidad.qmd
      - Evolución.qmd
      - Distribución Territorial.qmd
      - Actividades productivas.qmd
      - Comercialización.qmd
      - Características socio-demográficas de las personas registradas.qmd
      - Características del predio productivo.qmd
      - Pertenencia de los Naf a organizaciones.qmd
    page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

